### ISSUE TITLE
SemanticSearch.py error

### ISSUE THREAD

**Issue by ai-motive** [BM-K/KoSimCSE#1]
안녕하세요~
`SemanticSearch.py` 수행시 `get_pytorch_kobert_model()` 내에서 model, voc 다운로드시 url이 막혀 다음과 같은 에러가 발생합니다.

```
Traceback (most recent call last):
  File "/home/motive/PycharmProjects/KoSimCSE_SKT/KoBERT/kobert/utils.py", line 46, in download
    response = requests.get(url, stream=True)
  File "/home/motive/anaconda3/envs/KoSimCSE_SKT/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/motive/anaconda3/envs/KoSimCSE_SKT/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/motive/anaconda3/envs/KoSimCSE_SKT/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/motive/anaconda3/envs/KoSimCSE_SKT/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/motive/anaconda3/envs/KoSimCSE_SKT/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kobert.blob.core.windows.net', port=443): Max retries exceeded with url: /models/kobert/pytorch/kobert_v1.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2ca9d28a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

혹시 사전에 다운로드 받아놓은 model, voc 파일이 있다면 공유 받을수 있을지, 다른 우회 방법이 있는지 문의 드립니다~

아래 경로의 유사 error를 찾아 사전 packaging된 model 및 voc 파일을 로드해도 또다른 pkg. dependancy 문제 및 error가 발생하여 이렇게 문의 드립니다.
(참고한 repo. : https://github.com/SKTBrain/KoBERT, https://github.com/SKTBrain/KoBERT/tree/master/kobert_hf)

**Comment by ai-motive** [comment]
url이 복원되어 이슈 닫도록 하겠습니다~
